---
title: Gapminder Data in the HarvardX Data Science Program
author: Dane Hager
date: '2018-04-15'
slug: first-post
categories:
  - HarvardX Data Science
tags:
  - Gapminder
  - Visualization
---

In working through the HarvardX Data Science program, we studied the gapminder data set to look at life expectancy rates across countries. So, firstly, we load the packages:

```{r echo false}
library(tidyverse)
library(dslabs)
```

Then, we run the code (some of my notes included) to create a graphic of the comparison of the life expectancies for the US and Canada over the years.

```{r}
data(gapminder)
countries <- c("United States", "Canada") #creates an easier way to manage filtering by a set of selections
labels <- data.frame(country=countries, x=c(2010, 2000), y=c(77,80.5)) #x and y variables tell where to put each label
gapminder %>% filter(country %in% countries) %>% 
  ggplot(aes(year, life_expectancy, col=country))+
  geom_line() +
  geom_text(data=labels, aes(x, y, label=country), size=5) + 
  theme(legend.position="none")
```
